name: gitversion

env:
  NETCORE_VERSION: 5.0.101
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  push:
    branches: 
    - $default-branch
    - release/*
  workflow_dispatch:
    inputs: {}

jobs:
  gitversion:
    name: gitversion
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: actions/setup-dotnet@v1
      name: dotnet installer
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
    - name: dotnet tool restore
      run: dotnet tool restore
      shell: bash
    - name: gitversion
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
       dotnet gitversion